import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono NerdFont", style = "Medium" }
bold = { family = "JetBrainsMono NerdFont", style = "ExtraBold" }
size = 12
